drop schema if exists library cascade;
create schema if not exists library;

CREATE TABLE library.books
(
    id               integer GENERATED BY DEFAULT AS IDENTITY,
    isbn             character varying(13)  NOT NULL,
    title            character varying(255) NOT NULL,
    author           character varying(255) NOT NULL,
    publisher        character varying(255),
    genre            character varying(50),
    description      text,
    language         character varying(50)    DEFAULT ('English'::character varying),
    format           character varying(50),
    created_at       timestamp with time zone DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT books_pkey PRIMARY KEY (id)
);

CREATE TABLE library.libraryuser
(
    id              integer GENERATED BY DEFAULT AS IDENTITY,
    first_name      character varying(100) NOT NULL,
    last_name       character varying(100) NOT NULL,
    email           character varying(255) NOT NULL UNIQUE,
    phone           character varying(20),
    address         text,
    is_active       boolean DEFAULT TRUE,
    created_at      timestamp with time zone DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT libraryuser_pkey PRIMARY KEY (id)
);

CREATE TABLE library.loans
(
    id              integer GENERATED BY DEFAULT AS IDENTITY,
    book_id         integer NOT NULL,
    user_id         integer NOT NULL,
    return_date     timestamp with time zone,
    is_returned     boolean DEFAULT FALSE,
    created_at      timestamp with time zone DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT book_loans_pkey PRIMARY KEY (id),
    CONSTRAINT fk_book FOREIGN KEY (book_id) REFERENCES library.books(id),
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES library.libraryuser(id)
);

CREATE UNIQUE INDEX books_isbn_key ON library.books (isbn);
CREATE INDEX idx_books_author ON library.books (author);
CREATE INDEX idx_books_isbn ON library.books (isbn);
CREATE INDEX idx_books_title ON library.books (title);
CREATE INDEX idx_libraryuser_email ON library.libraryuser (email);
CREATE INDEX idx_book_loans_book_id ON library.loans (book_id);
CREATE INDEX idx_book_loans_user_id ON library.loans (user_id);
CREATE INDEX idx_book_loans_return_date ON library.loans (return_date);